version: 2

sources:
 
  - name: DEV_CUST
   
    database: "{% if target.database == 'DEV_EDW' -%} DEV_RAW{% elif target.database == 'TEST_EDW' -%} TEST_RAW{% elif target.database == 'PROD_EDW' -%} PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: CUSTOMER
        identifier: CUSTOMER
     